lib/sonata-project/ecommerce/src/ProductBundle/Form/Type/ApiProductType.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Sonata Project package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sonata\ProductBundle\Form\Type;

use Sonata\Component\Product\Pool;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * @author Vincent Composieux <vincent.composieux@gmail.com>
 */
class ApiProductType extends AbstractType
{
    /**
     * @var Pool
     */
    protected $productPool;

    /**
     * @param Pool $productPool
     */
    public function __construct(Pool $productPool)
    {
        $this->productPool = $productPool;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        if ($options['provider_name']) {
            $provider = $this->productPool->getProvider($options['provider_name']);
            $provider->buildForm($builder, $options);
        }
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => null,
            'csrf_protection' => false,
            'provider_name' => null,
        ]);
    }

    public function getBlockPrefix()
    {
        return 'sonata_product_api_form_product';
    }

    public function getName()
    {
        return $this->getBlockPrefix();
    }

    public function getParent()
    {
        return ApiProductParentType::class;
    }
}

lib/sonata-project/ecommerce/src/ProductBundle/Controller/CategoryController.php
<?php

declare(strict_types=1);

/*
 * This file is part of the Sonata Project package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sonata\ProductBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class CategoryController extends Controller
{
    /**
     * @param null $category
     * @param int  $depth
     * @param int  $deep
     *
     * @return Response
     */
    public function listSideMenuCategoriesAction($category = null, $depth = 1, $deep = 0)
    {
        $category = $category ?: $this->get('sonata.classification.manager.category')->getRootCategory();

        return $this->render('SonataProductBundle:Category:side_menu_category.html.twig', [
          'root_category' => $category,
          'depth' => $depth,
          'deep' => $deep + 1,
        ]);
    }
}

lib/sonata-project/ecommerce/src/ProductBundle/Resources/views/Category/side_menu_category.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

<ul>
    {% for category in root_category.getChildren() %}
        <li>
            <a href="{{ url('sonata_catalog_index', {'category_slug': category.slug, 'category_id': category.id}) }}">{{ category.name }}</a>

            {% if category.hasChildren and deep < depth%}

                {% render controller('SonataProductBundle:Category:listSideMenuCategories', {
                    'category': category,
                    'deep' : deep,
                    'depth': depth
                }) %}

            {% endif %}

        </li>
    {% endfor %}
</ul>